name: Handler Action

on:
  check_run:
    types:
      - requested_action

jobs:
  rules:
    runs-on: ubuntu-latest
    environment: safe
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: denoland/setup-deno@v1
      - run: bun install --production
      - run: bun run action-event
        env:
          ACTION_NAME: ${{github.event.requested_action }}
          ACTION_PAYLOAD: ${{ toJson(github.event.action) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
