name: Pull Request Main
on:
  pull_request_target:
    types:
      [
        opened,
        reopened,
        labeled,
        unlabeled,
        assigned,
        unassigned,
        ready_for_review,
        review_requested,
        review_request_removed,
        synchronize,
        edited,
        locked,
        auto_merge_disabled,
        auto_merge_enabled,
        converted_to_draft,
        unlocked,
      ]
    branches:
      - main
jobs:
  rules:
    if: false
    runs-on: ubuntu-latest
    environment: safe
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: denoland/setup-deno@v1
      - run: bun install --production
      - run: bun run check
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          SHA: '${{ github.event.pull_request.head.sha }}'
          OTHER: ${{ toJSON(github.event.pull_request) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
